version: '3.8'

services:
  nextjs:
    build:
      context: ./fullstack_issue
    volumes:
      - ./fullstack_issue:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: always
    command: npm run dev

  fastapi:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
    - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload